version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.8
     steps:
       - checkout
       - run: echo $G0PATH
       - run: go build
       - run: go run main.go
       - run: go test
