version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.8
     steps:
       - checkout
       - go get "github.com/stretchr/testify/assert"
       - run: go run main.go
       - run: go test

